(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [binpow]: function definitions *)
module Binpow.Funs
open Primitives
include Binpow.Types
include Binpow.Clauses

#set-options "--z3rlimit 50 --fuel 1 --ifuel 1"

(** [binpow::binpow]: forward function *)
let rec binpow_fwd
  (a : u32) (n : u32) : Tot (result u32) (decreases (binpow_decreases a n)) =
  if n = 0
  then Return 1
  else
    let* i = u32_rem n 2 in
    if i = 1
    then
      let* i0 = u32_sub n 1 in
      let* i1 = u32_div i0 2 in
      let* half_pow = binpow_fwd a i1 in
      let* i2 = u32_mul half_pow half_pow in
      u32_mul i2 a
    else
      let* i0 = u32_div n 2 in
      let* half_pow = binpow_fwd a i0 in
      u32_mul half_pow half_pow

