(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [binpow]: templates for the decreases clauses *)
module Binpow.Clauses.Template
open Primitives
open Binpow.Types

#set-options "--z3rlimit 50 --fuel 1 --ifuel 1"

(** [binpow::binpow]: decreases clause *)
unfold let binpow_decreases (a : u32) (n : u32) : nat = admit ()

